export const LEVELS = [
  {
    id: "level1",
    title: "Neon Drift",
    subtitle: "Deep-space starter route",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Medium",
    tagline: "Ease into the orbit. Clean right-angle turns and readable four-beat phrases.",
    beatmapUrl: "./beatmaps/dist/level1.beatstar.json",
  },
  {
    id: "level2",
    title: "Nebula Run",
    subtitle: "Storm-lit syncopation",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Advanced",
    tagline: "Call-and-response turns and sharper accent reversals in a violet storm.",
    beatmapUrl: "./beatmaps/dist/level2.beatstar.json",
  },
  {
    id: "level3",
    title: "Crystal Orbit",
    subtitle: "Angular hard route",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Hard",
    tagline: "Hex loops and eighth-note staples cut by triplet crystal runs. The real test.",
    beatmapUrl: "./beatmaps/dist/level3.beatstar.json",
  },
  {
    id: "level4",
    title: "Solar Flare",
    subtitle: "Burning orbit gauntlet",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Expert",
    tagline: "Relentless eighth-note geometry with sixteenth sprint corridors. Bring gloves.",
    beatmapUrl: "./beatmaps/dist/level4.beatstar.json",
  },
  {
    id: "level5",
    title: "Void Walker",
    subtitle: "Into the abyss",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Extreme",
    tagline: "Triplet stairs and void sprints broken by sudden half-time calm. Survive it.",
    beatmapUrl: "./beatmaps/dist/level5.beatstar.json",
  },
  {
    id: "level6",
    title: "Bloom Garden",
    subtitle: "Rosette artwork route",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Scenic",
    tagline: "The track blossoms into rosettes, vines, and orbit rings. Play the artwork.",
    beatmapUrl: "./beatmaps/dist/level6.beatstar.json",
  },
  {
    id: "level7",
    title: "Helix Tower",
    subtitle: "Coiling staircase climb",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Scenic+",
    tagline: "Coiling staircases and DNA arcs wrap the screen like a spiral tower.",
    beatmapUrl: "./beatmaps/dist/level7.beatstar.json",
  },
  {
    id: "level8",
    title: "Hyper Bloom",
    subtitle: "Ultra spam mandala",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Ultra Spam",
    tagline: "Mash three keys and the mandala paints itself. Pure spam, pure spectacle.",
    beatmapUrl: "./beatmaps/dist/level8.beatstar.json",
  },
  {
    id: "level9",
    title: "Comet Coil",
    subtitle: "Ultra spam helix dive",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Ultra Spam",
    tagline: "A green comet drills endless coils at mash speed. Keep the keys hot.",
    beatmapUrl: "./beatmaps/dist/level9.beatstar.json",
  },
  {
    id: "level10",
    title: "Star Cascade",
    subtitle: "Maximum spam meteor rail",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Ultra Spam",
    tagline: "The old speed king, now faster: ~17 presses a second. Three keys minimum.",
    beatmapUrl: "./beatmaps/dist/level10.beatstar.json",
  },
  {
    id: "level11",
    title: "Inferno Core",
    subtitle: "Mega spam magma dive",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Mega Spam",
    tagline: "Dive through a volcanic core at ~18 presses a second. The heat is real.",
    beatmapUrl: "./beatmaps/dist/level11.beatstar.json",
  },
  {
    id: "level12",
    title: "Warp Tunnel",
    subtitle: "Giga spam hyperdrive",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Giga Spam",
    tagline: "A collapsing hyperspace tube at 20 presses a second. Blink and you crash.",
    beatmapUrl: "./beatmaps/dist/level12.beatstar.json",
  },
  {
    id: "level13",
    title: "Singularity",
    subtitle: "Omega spam event horizon",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Omega Spam",
    tagline: "~22 presses a second into a black hole. Nothing faster exists.",
    beatmapUrl: "./beatmaps/dist/level13.beatstar.json",
  },
  {
    id: "level14",
    title: "Meltdown",
    subtitle: "Hyper spam reactor breach",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Hyper Spam",
    tagline: "~5x past the old ceiling. Humanly impossible — flip on No Death and watch.",
    beatmapUrl: "./beatmaps/dist/level14.beatstar.json",
  },
  {
    id: "level15",
    title: "Overdrive",
    subtitle: "Turbo spam solar sprint",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Turbo Spam",
    tagline: "A sun flaring faster than the eye can track. No Death spectacle.",
    beatmapUrl: "./beatmaps/dist/level15.beatstar.json",
  },
  {
    id: "level16",
    title: "Detonator",
    subtitle: "Nitro spam circuit overload",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Nitro Spam",
    tagline: "A circuit board overloading to failure. Pure light show.",
    beatmapUrl: "./beatmaps/dist/level16.beatstar.json",
  },
  {
    id: "level17",
    title: "Cataclysm",
    subtitle: "Plasma spam void tear",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Plasma Spam",
    tagline: "A void swallowing tiles faster than they can appear.",
    beatmapUrl: "./beatmaps/dist/level17.beatstar.json",
  },
  {
    id: "level18",
    title: "Annihilator",
    subtitle: "Quantum spam meteor storm",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Quantum Spam",
    tagline: "A meteor storm of tiles at quantum density.",
    beatmapUrl: "./beatmaps/dist/level18.beatstar.json",
  },
  {
    id: "level19",
    title: "Supernova",
    subtitle: "Nova spam prism blast",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Nova Spam",
    tagline: "Light shattering into a rainbow supernova of tiles.",
    beatmapUrl: "./beatmaps/dist/level19.beatstar.json",
  },
  {
    id: "level20",
    title: "Event Horizon",
    subtitle: "Quasar spam helix tower",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Quasar Spam",
    tagline: "A DNA tower spun into a solid ribbon of light.",
    beatmapUrl: "./beatmaps/dist/level20.beatstar.json",
  },
  {
    id: "level21",
    title: "Oblivion",
    subtitle: "Pulsar spam hyperdrive",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Pulsar Spam",
    tagline: "A hyperspace tube collapsing at the edge of light.",
    beatmapUrl: "./beatmaps/dist/level21.beatstar.json",
  },
  {
    id: "level22",
    title: "Ragnarok",
    subtitle: "Cosmic spam magma dive",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Cosmic Spam",
    tagline: "A magma core erupting a near-solid stream of tiles.",
    beatmapUrl: "./beatmaps/dist/level22.beatstar.json",
  },
  {
    id: "level23",
    title: "Heat Death",
    subtitle: "The final 20x singularity",
    duration: 150,
    durationLabel: "2:30",
    difficulty: "Heat Death",
    tagline: "~20x the old ceiling. The fastest rail that can exist. The end.",
    beatmapUrl: "./beatmaps/dist/level23.beatstar.json",
  },
];

export const TIMING_WINDOWS = {
  perfect: 0.09,
  good: 0.17,
  miss: 0.27,
};

export const DEFAULT_SETTINGS = {
  calibrationMs: 0,
  reduceCamera: false,
  missMode: "safety",
  allowedMisses: 2,
  noDeath: false,
};

export const TRACK_ORDER = [
  "Breakneck_Descent.mp3",
  "Clockwork_Sprint.mp3",
  "Concrete_Lung.mp3",
  "Gravity_Lock.mp3",
  "Gravity_Locked.mp3",
  "Iron_Lung.mp3",
  "Iron_Teeth_Glass_Keys.mp3",
  "Overclocked_Nerve.mp3",
  "Sun_Drenched_Logic.mp3",
  "Synchronized_Glide.mp3",
  "A_Violent_Grace.mp3",
  "Cold_Geometry.mp3",
  "Game_Over_at_Noon.mp3",
  "Gears_Grind_Teeth.mp3",
  "High_Altitude_Glide.mp3",
  "Midday_Highway.mp3",
  "Pendulum_Error.mp3",
  "Sugar_Rush_Mode.mp3",
  "The_Felt_Against_the_Rain.mp3",
  "The_Iron_Mandate.mp3",
];
